import type { Metadata } from "next";
import StyledComponentsRegistry from './lib/registry'
import Header from "./components/header";
import { GlobalStyle } from "./global";
import Head from "next/head";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Rubik:ital,wght@0,300..900;1,300..900&display=swap" rel="stylesheet"/> 
      </Head>
      <StyledComponentsRegistry>
        <GlobalStyle />
        <body>
          <Header />
          {children}
        </body>
      </StyledComponentsRegistry>
    </html>
  );
}
